# Generated by Django 6.0.2 on 2026-02-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Company name', max_length=255, verbose_name='Название компании')),
                ('image_url', models.CharField(max_length=500, verbose_name='URl фото')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.CharField(max_length=500, verbose_name='URL фото'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок поста'),
        ),
    ]
